### PR TITLE
Comments in "Notes" slides, playing with outlier detection

### PR DESCRIPTION
**Pull request by betatim**
I made some comments mostly in "notes" type slides. Main points:
- nice!
- python 3(.5) plus scikit-learn master might lose a lot of people
- adding a small thing about how to get ROOT data into numpy arrays will help with people caring to use it. It isn't sklearn specific I know. However there will be two types, those who can work out that `root_numpy` exists themselves and those that won't. The former will also know about scikit-learn already and be a minority.
- iforest can nearly tell even from odd digits!
- exception when max_samples<1. for iforest, wat?
- binder is borked?

### CODE REVIEW

**Comment by glouppe** [comment]
Thanks a lot Tim for the review! I am merging and making changes from your comments.

**Comment by glouppe** [comment]
(I'll reply later more specifically as I go through)

**Comment by betatim** [comment]
:cake: for breakfast! (if only)

**Comment by glouppe** [comment]
For the length, I agree it may be a bit too long, though I have 2 to 3 hours to cover everything. I might skip things rather removing stuff from the notebook, so that interested people can still learn more than what I'll be effectively presenting.

**Comment by glouppe** [comment]
For Python 3.5+Scikit-Learn 0.18-dev, it is true that it may be a barrier. I think I'll downgrade to 0.17 at least.

I was also thinking about defining a custom environment.yml for the Binder.

**Comment by betatim** [comment]
Skipping is also a good option. It is a nice reference collection to go back to later.

binder: good point for the tutorial, I was thinking of how people could "take it home".

For the lhcb-starterkit I am trying to build a legacy python conda env that "just works" on lxplus. I can donate the `env.yml` for that (once it works). The bits that require `python` are in the plotting parts like: `xx, yy = np.meshgrid(np.linspace(*xlim, n_steps), np.linspace(*ylim, n_steps))` which is more ugly on legacy python. No good advice beyond the one you don't want to hear: make it legacy python to maximise number of people using it :smile:

**Pull request merged**
